
###
GET http://localhost:5000/pulsa/

###
POST  http://localhost:5000/pulsa/create
Content-Type: application/json

{
    "Harga": 12000,
    "BesarPulsa" : 12000
}

###
GET http://localhost:5000/pulsa/getall

###
GET http://localhost:5000/pulsa/getid/ID

### 
PUT http://localhost:5000/pulsa/edit/ID
Content-Type: application/json

{
    "Harga": 12000,
    "BesarPulsa" : 12000
}

###
DELETE http://localhost:5000/pulsa/delete/60940135839ad427217d8258

###
POST  http://localhost:5000/auth/register
Content-Type: application/json

{
    "UserName": "Rizqy",
    "Password" : "hahah"
}

###
POST  http://localhost:5000/auth/login
Content-Type: application/json

{
    "UserName": "Rizqy",
    "Password" : "hahah"
}
